### PR TITLE
aml-vnc: Make IPV6 listen port consistent with IPV4

### PR DESCRIPTION
**Pull request by BackZhao**

### CODE REVIEW

**Comment by vpeter4** [comment]
Correct the changelog as I wrote in previous PR and then it will be good to go :)

**Comment by BackZhao** [comment]
> 

Sorry for my misunderstanding, I've corrected the changelog😁

**Comment by BackZhao** [comment]
> Correct the changelog as I wrote in previous PR and then it will be good to go :)

Sorry for my misunderstanding, I've corrected the changelog😁

**Comment by vpeter4** [comment]
Thank you. I just noticed that this package is a mess and I will fix everything over the day. And tomorrow should addon be build already.

**Comment by BackZhao** [comment]
> Thank you. I just noticed that this package is a mess and I will fix everything over the day. And tomorrow should addon be build already.

That's wonderful, I would learn a lot from your work since I'm a newcomer for CoreELEC :)

**Pull request merged**
